import json

from airlines_reader.airlines.model import AirlineModelBuilder

if __name__ == '__main__':
    builder = AirlineModelBuilder({'data': {'getMYBTripDetails': {'originalResponse': {
        'pnr': {'reloc': 'HEEPIS', 'iropAffected': False, 'itinerary': {'@type': 'Itinerary', '@id': '1',
                                                                        'itineraryParts': [
                                                                            {'@type': 'ItineraryPart', '@id': '2',
                                                                             'segments': [
                                                                                 {'@type': 'Segment', '@id': '3',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 340,
                                                                                  'cabinClass': 'Economy',
                                                                                  'equipment': '350',
                                                                                  'flight': {'flightNumber': 920,
                                                                                             'operatingFlightNumber': 920,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'ET',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'ACC', 'destination': 'ADD',
                                                                                  'departure': '2024-11-02T12:20:00',
                                                                                  'arrival': '2024-11-02T21:00:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False},
                                                                                 {'@type': 'Segment', '@id': '4',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 400,
                                                                                  'cabinClass': 'Economy',
                                                                                  'equipment': '787',
                                                                                  'flight': {'flightNumber': 686,
                                                                                             'operatingFlightNumber': 686,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'ET',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'ADD', 'destination': 'DEL',
                                                                                  'departure': '2024-11-02T22:55:00',
                                                                                  'arrival': '2024-11-03T08:05:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False},
                                                                                 {'@type': 'Segment', '@id': '5',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 195,
                                                                                  'cabinClass': 'Economy',
                                                                                  'equipment': '321',
                                                                                  'flight': {'flightNumber': 1763,
                                                                                             'operatingFlightNumber': 831,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'AI',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'DEL', 'destination': 'COK',
                                                                                  'departure': '2024-11-03T11:20:00',
                                                                                  'arrival': '2024-11-03T14:35:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False,
                                                                                  'otherAirlineRecordLocator': 'SEKMD7'}],
                                                                             'stops': 2, 'totalDuration': 1245,
                                                                             'connectionInformations': [
                                                                                 {'@id': '6', 'duration': 115,
                                                                                  'changeOfAirport': False},
                                                                                 {'@id': '7', 'duration': 195,
                                                                                  'changeOfAirport': False}],
                                                                             'bookingClass': 'U'},
                                                                            {'@type': 'ItineraryPart', '@id': '8',
                                                                             'segments': [
                                                                                 {'@type': 'Segment', '@id': '9',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 150,
                                                                                  'cabinClass': 'Economy',
                                                                                  'flight': {'flightNumber': 1751,
                                                                                             'operatingFlightNumber': 699,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'AI',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'COK', 'destination': 'BOM',
                                                                                  'departure': '2025-02-16T21:40:00',
                                                                                  'arrival': '2025-02-17T00:10:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False,
                                                                                  'otherAirlineRecordLocator': 'SEKMD7'},
                                                                                 {'@type': 'Segment', '@id': '10',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 320,
                                                                                  'cabinClass': 'Economy',
                                                                                  'equipment': '789',
                                                                                  'flight': {'flightNumber': 611,
                                                                                             'operatingFlightNumber': 611,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'ET',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'BOM', 'destination': 'ADD',
                                                                                  'departure': '2025-02-17T04:05:00',
                                                                                  'arrival': '2025-02-17T06:55:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False},
                                                                                 {'@type': 'Segment', '@id': '11',
                                                                                  'segmentOfferInformation': {
                                                                                      'flightsMiles': 0,
                                                                                      'awardFare': False},
                                                                                  'duration': 340,
                                                                                  'cabinClass': 'Economy',
                                                                                  'equipment': '350',
                                                                                  'flight': {'flightNumber': 921,
                                                                                             'operatingFlightNumber': 921,
                                                                                             'airlineCode': 'ET',
                                                                                             'operatingAirlineCode': 'ET',
                                                                                             'stopAirports': []},
                                                                                  'origin': 'ADD', 'destination': 'ACC',
                                                                                  'departure': '2025-02-17T08:40:00',
                                                                                  'arrival': '2025-02-17T11:20:00',
                                                                                  'segmentStatusCode': {'code': 'USED',
                                                                                                        'segmentStatus': 'FLOWN'},
                                                                                  'bookingClass': 'U',
                                                                                  'layoverDuration': 0,
                                                                                  'fareBasis': 'ULDESGH',
                                                                                  'subjectToGovernmentApproval': False}],
                                                                             'stops': 2, 'totalDuration': 1150,
                                                                             'connectionInformations': [
                                                                                 {'@id': '12', 'duration': 235,
                                                                                  'changeOfAirport': False},
                                                                                 {'@id': '13', 'duration': 105,
                                                                                  'changeOfAirport': False}],
                                                                             'bookingClass': 'U'}]}, 'passengers': [
            {'@id': '14', 'passengerIndex': 1, 'passengerNameNumber': '01.01',
             'passengerDetails': {'firstName': 'OBED', 'lastName': 'ASAMOAH', 'prefix': 'MR'},
             'passengerInfo': {'dateOfBirth': '1990-04-17', 'gender': 'MALE', 'type': 'ADT', 'emails': [],
                               'phones': []}, 'preferences': {
                'specialPreferences': {'mealPreference': '', 'seatPreference': '',
                                       'specialRequests': ['TKNE', 'TKNE', 'TKNE', 'TKNE', 'TKNE', 'TKNE', 'TKNE'],
                                       'specialServiceRequestRemarks': [{'code': 'TKNE',
                                                                         'description': 'ET HK1 ACCADD0920U02NOV/0716097233795C1/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'ACC', 'destination': 'ADD',
                                                                              'departure': '2024-11-02T12:20:00',
                                                                              'arrival': '2024-11-02T21:00:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 ADDDEL0686U02NOV/0716097233795C2/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'ADD', 'destination': 'DEL',
                                                                              'departure': '2024-11-02T22:55:00',
                                                                              'arrival': '2024-11-03T08:05:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 DELCOK1763U03NOV/0716097233795C3/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'DEL', 'destination': 'COK',
                                                                              'departure': '2024-11-03T11:20:00',
                                                                              'arrival': '2024-11-03T14:35:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 COKBOM1751U16FEB/0716097233795C4/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'COK', 'destination': 'BOM',
                                                                              'departure': '2025-02-16T21:40:00',
                                                                              'arrival': '2025-02-17T00:10:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 BOMADD0611U17FEB/0716097233796C1/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'COK', 'destination': 'BOM',
                                                                              'departure': '2025-02-16T21:40:00',
                                                                              'arrival': '2025-02-17T00:10:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 ADDACC0921U17FEB/0716097233796C2/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'BOM', 'destination': 'ADD',
                                                                              'departure': '2025-02-17T04:05:00',
                                                                              'arrival': '2025-02-17T06:55:00'}]},
                                                                        {'code': 'TKNE',
                                                                         'description': 'ET HK1 COKBOM1751U16FEB/0716097233795C4/795-796',
                                                                         'segmentKeys': [
                                                                             {'origin': 'ADD', 'destination': 'ACC',
                                                                              'departure': '2025-02-17T08:40:00',
                                                                              'arrival': '2025-02-17T11:20:00'}]}]},
                'frequentFlyer': [{'airline': 'ET', 'number': '10001664492', 'tierLevel': 'Silver', 'tierNumber': 2}]},
             'documentInfo': {'issuingCountry': 'GHA', 'documentNumber': 'G2836858', 'documentType': 'P',
                              'nationality': 'GHA', 'expirationDate': '2030-03-31', 'dateOfBirth': '1990-04-17'},
             'allDocumentInfos': [
                 {'issuingCountry': 'IN', 'issueDate': '2024-11-01', 'documentNumber': '755', 'documentType': 'V',
                  'expirationDate': '2038-08-09'}],
             'visaInfo': {'issuingCountry': 'IN', 'issueDate': '2024-11-01', 'expiryDate': '2038-08-09',
                          'documentNumber': '755', 'issuePlace': 'GHANA'}}], 'documents': [{'@id': '15',
                                                                                            'documentDetails': {
                                                                                                'documentType': 'VCR',
                                                                                                'documentNumber': '0716097233795-96',
                                                                                                'countryCode': 'GH',
                                                                                                'stationLocation': 'ACC',
                                                                                                'issueDate': '2024-09-13',
                                                                                                'currencyCode': 'GHS'},
                                                                                            'passenger': {'@ref': '14'},
                                                                                            'coupons': [
                                                                                                {'couponNumber': 1,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '3'}},
                                                                                                {'couponNumber': 2,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '4'}},
                                                                                                {'couponNumber': 3,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '5'}},
                                                                                                {'couponNumber': 4,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '9'}},
                                                                                                {'couponNumber': 5,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '10'}},
                                                                                                {'couponNumber': 6,
                                                                                                 'couponStatus': 'USED',
                                                                                                 'travelPart': {
                                                                                                     '@ref': '11'}}]}],
                'travelPartsAdditionalDetails': [{'travelPart': {'@ref': '3'}, 'passengers': [
                    {'passenger': {'@ref': '14'}, 'checkedInBaggage': {'baggageAllowanceDefinition': [
                        {'totalUnits': '2', 'baggageRestrictions': [], 'baggageAllowanceType': 'STANDARD'}]},
                     'seat': {'seatCode': '25D'}, 'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []},
                                                 {'travelPart': {'@ref': '4'}, 'passengers': [
                                                     {'passenger': {'@ref': '14'}, 'checkedInBaggage': {
                                                         'baggageAllowanceDefinition': [
                                                             {'totalUnits': '2', 'baggageRestrictions': [],
                                                              'baggageAllowanceType': 'STANDARD'}]},
                                                      'seat': {'seatCode': '25A'},
                                                      'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []},
                                                 {'travelPart': {'@ref': '5'}, 'passengers': [
                                                     {'passenger': {'@ref': '14'}, 'checkedInBaggage': {
                                                         'baggageAllowanceDefinition': [
                                                             {'totalUnits': '2', 'baggageRestrictions': [],
                                                              'baggageAllowanceType': 'STANDARD'}]},
                                                      'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []},
                                                 {'travelPart': {'@ref': '9'}, 'passengers': [
                                                     {'passenger': {'@ref': '14'}, 'checkedInBaggage': {
                                                         'baggageAllowanceDefinition': [
                                                             {'totalUnits': '2', 'baggageRestrictions': [],
                                                              'baggageAllowanceType': 'STANDARD'}]},
                                                      'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []},
                                                 {'travelPart': {'@ref': '10'}, 'passengers': [
                                                     {'passenger': {'@ref': '14'}, 'checkedInBaggage': {
                                                         'baggageAllowanceDefinition': [
                                                             {'totalUnits': '2', 'baggageRestrictions': [],
                                                              'baggageAllowanceType': 'STANDARD'}]},
                                                      'seat': {'seatCode': '27A'},
                                                      'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []},
                                                 {'travelPart': {'@ref': '11'}, 'passengers': [
                                                     {'passenger': {'@ref': '14'}, 'checkedInBaggage': {
                                                         'baggageAllowanceDefinition': [
                                                             {'totalUnits': '2', 'baggageRestrictions': [],
                                                              'baggageAllowanceType': 'STANDARD'}]},
                                                      'seat': {'seatCode': '25A'},
                                                      'eticketNumber': '0716097233795-96'}], 'eligibilities': [],
                                                  'eligibilitiesCodes': {}, 'coLocatedAirports': []}], 'payments': [],
                'documentPaymentDetails': [{'document': {'@ref': '15'}, 'endorsements': ['NON-ENDO', 'PENALTIES APPLY'],
                                            'tourCode': 'ACCDI005',
                                            'payments': [{'paymentCode': 'CASH', 'paymentType': 'CASH'}],
                                            'total': {'alternatives': []}}],
                'priceBreakdown': {'label': 'totalReservationPrice',
                                   'price': {'alternatives': [[{'amount': 15698.2, 'currency': 'GHS'}]]},
                                   'subElements': [{'label': 'farePrice',
                                                    'price': {'alternatives': [[{'amount': 7592, 'currency': 'GHS'}]]},
                                                    'breakdownElementAssignment': {'travelPart': {'@ref': '1'}},
                                                    'subElements': [{'label': 'BASE', 'price': {
                                                        'alternatives': [[{'amount': 7592, 'currency': 'GHS'}]]},
                                                                     'breakdownElementAssignment': {
                                                                         'passenger': {'@ref': '14'},
                                                                         'passengerType': 'ADT'},
                                                                     'additionalContext': {}}],
                                                    'additionalContext': {}},
                                                   {'label': 'discountPrice', 'price': {'alternatives': []},
                                                    'breakdownElementAssignment': {'travelPart': {'@ref': '1'}},
                                                    'additionalContext': {}}, {'label': 'taxesPrice', 'price': {
                                           'alternatives': [[{'amount': 8106.2, 'currency': 'GHS'}]]},
                                                                               'breakdownElementAssignment': {
                                                                                   'travelPart': {'@ref': '1'}},
                                                                               'subElements': [{'label': 'GH',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 1575,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 1575,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'P2',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 223.1,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 223.1,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'IN',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 141.3,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 141.3,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'S9',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 39.4,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 39.4,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'L3',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 31.6,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 31.6,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'YQ',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 472.8,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 472.8,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'YR',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 5197.6,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 5197.6,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'G5',
                                                                                                'price': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 362.4,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [[{
                                                                                                        'amount': 362.4,
                                                                                                        'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}},
                                                                                               {'label': 'S2',
                                                                                                'price': {
                                                                                                    'alternatives': [
                                                                                                        [{'amount': 63,
                                                                                                          'currency': 'GHS'}]]},
                                                                                                'pricePerUnit': {
                                                                                                    'alternatives': [
                                                                                                        [{'amount': 63,
                                                                                                          'currency': 'GHS'}]]},
                                                                                                'additionalContext': {}}],
                                                                               'additionalContext': {}},
                                                   {'label': 'feesPrice', 'price': {'alternatives': []},
                                                    'additionalContext': {}},
                                                   {'label': 'ancillariesPrice', 'price': {'alternatives': []},
                                                    'additionalContext': {}},
                                                   {'label': 'seatsPrice', 'price': {'alternatives': []},
                                                    'additionalContext': {}},
                                                   {'label': 'obFeesPrice', 'price': {'alternatives': []},
                                                    'additionalContext': {}},
                                                   {'label': 'upgradePrice', 'price': {'alternatives': []},
                                                    'additionalContext': {}}], 'additionalContext': {}},
                'contact': {'emails': [], 'phones': [], 'addresses': []},
                'otherServiceInformation': ['OSI ET CTCT ACC  233 302 785876 SHIVOHUM TRAVEL SERVICES',
                                            'OSI ET *** PREV TIME FOR ET1751U 16FEB COKBOM  905P 1125P',
                                            'OSI ET *** PREV TIME FOR ET1751U 16FEB COKBOM  850P 1120P',
                                            'OSI ET *** PREV TIME FOR ET1751U 16FEB COKBOM  855P 1125P',
                                            'OSI ET *** PREV TIME FOR ET1751U 16FEB COKBOM  925P 1155P',
                                            'OSI YY CTCT ACC  233 302 785876 SHIVOHUM TRAVEL SERVICES'],
                'fareRulesResult': {'segmentFareRules': []}, 'remarks': [],
                'specialServiceRequests': [{'code': 'ADTK', 'description': 'TO ET BY 18SEP 1700 OTHERWISE WILL BE XLD'},
                                           {'code': 'ADTK', 'description': 'TO ET BY 19SEP 1300 OTHERWISE WILL BE XLD'},
                                           {'code': 'SEAT', 'description': 'LK1 ADDACC0921U17FEB.25A/RS'},
                                           {'code': 'OTHS', 'description': 'PLZ UPDATE ITIN BY XXL ALL HX SEGMENTS'},
                                           {'passengerIndex': 1, 'code': 'CTCM', 'description': '/233302785876'},
                                           {'passengerIndex': 1, 'code': 'CTCM', 'description': '/233302785876'},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 ACCADD0920U02NOV/0716097233795C1/795-796',
                                            'segmentKey': {'origin': 'ACC', 'destination': 'ADD',
                                                           'departure': '2024-11-02T12:20:00',
                                                           'arrival': '2024-11-02T21:00:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 ADDDEL0686U02NOV/0716097233795C2/795-796',
                                            'segmentKey': {'origin': 'ADD', 'destination': 'DEL',
                                                           'departure': '2024-11-02T22:55:00',
                                                           'arrival': '2024-11-03T08:05:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 DELCOK1763U03NOV/0716097233795C3/795-796',
                                            'segmentKey': {'origin': 'DEL', 'destination': 'COK',
                                                           'departure': '2024-11-03T11:20:00',
                                                           'arrival': '2024-11-03T14:35:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 COKBOM1751U16FEB/0716097233795C4/795-796',
                                            'segmentKey': {'origin': 'COK', 'destination': 'BOM',
                                                           'departure': '2025-02-16T21:40:00',
                                                           'arrival': '2025-02-17T00:10:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 BOMADD0611U17FEB/0716097233796C1/795-796',
                                            'segmentKey': {'origin': 'BOM', 'destination': 'ADD',
                                                           'departure': '2025-02-17T04:05:00',
                                                           'arrival': '2025-02-17T06:55:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 ADDACC0921U17FEB/0716097233796C2/795-796',
                                            'segmentKey': {'origin': 'ADD', 'destination': 'ACC',
                                                           'departure': '2025-02-17T08:40:00',
                                                           'arrival': '2025-02-17T11:20:00'}},
                                           {'passengerIndex': 1, 'code': 'TKNE',
                                            'description': 'ET HK1 COKBOM1751U16FEB/0716097233795C4/795-796',
                                            'segmentKey': {'origin': 'COK', 'destination': 'BOM',
                                                           'departure': '2025-02-16T21:40:00',
                                                           'arrival': '2025-02-17T00:10:00'}},
                                           {'passengerIndex': 1, 'code': 'DOCS', 'description': 'S1'},
                                           {'passengerIndex': 1, 'code': 'DOCO',
                                            'description': 'DOCO ET HK1//V/755/GHANA/01NOV24/IN//09AUG38'},
                                           {'passengerIndex': 1, 'code': 'DOCO',
                                            'description': 'DOCO ET HK1//V/VN2114159/GHANA//IN//14MAR25'}],
                'pseudoCity': {'pseudoCityCode': 'KMS', 'stationId': '24490082', 'bookingPseudoCityCode': 'TTY'},
                'bookingType': 'REVENUE', 'redemptionExchangePriceBreakdown': []},
        'tripOptions': [{'tripOption': 'SPLIT_MTO', 'ruleName': 'SPLIT_MTO_GUEST', 'enabled': True},
                        {'tripOption': 'ADD_INSURANCE_POSTBOOKING', 'ruleName': 'CONFIGURATION', 'enabled': False,
                         'failureReason': 'disabled'},
                        {'tripOption': 'CHECK_IN', 'ruleName': 'CHECKIN_GUEST', 'enabled': True},
                        {'tripOption': 'CANCEL_ITINERARY', 'ruleName': 'CANCELITINERARY_GUEST', 'enabled': True},
                        {'tripOption': 'PURCHASE_ON_HOLD_BOOKING', 'ruleName': 'BNPL_GUEST', 'enabled': False,
                         'failureReason': 'bnpl.allow'},
                        {'tripOption': 'CANCEL_FLIGHT', 'ruleName': 'CANCEL_GUEST', 'enabled': False,
                         'failureReason': 'usedTicket.disallow'},
                        {'tripOption': 'VOID', 'ruleName': 'VOID_GUEST', 'enabled': True},
                        {'tripOption': 'UPGRADE', 'ruleName': 'UPGRADE_GUEST', 'enabled': False,
                         'failureReason': 'usedTicket.disallow'},
                        {'tripOption': 'IROP', 'ruleName': 'CONFIGURATION', 'enabled': False,
                         'failureReason': 'disabled'},
                        {'tripOption': 'OFFLOAD', 'ruleName': 'OFFLOAD_GUEST', 'enabled': True},
                        {'tripOption': 'EXCHANGE_FLIGHT', 'ruleName': 'EXCHANGE_GUEST', 'enabled': False,
                         'failureReason': 'usedTicket.disallow'},
                        {'tripOption': 'ADD_MODIFY_SEATS', 'ruleName': 'SEATS_MTO_GUEST', 'enabled': True},
                        {'tripOption': 'EDIT_PASSENGER', 'ruleName': 'EDIT_PAX_DETAILS_GUEST', 'enabled': True},
                        {'tripOption': 'CANCEL_UPGRADE', 'ruleName': 'CANCEL_UPGRADE_GUEST', 'enabled': True},
                        {'tripOption': 'ADD_MODIFY_ANCILLARIES', 'ruleName': 'ANCILLARIES_MTO_GUEST', 'enabled': False,
                         'failureReason': 'codeshareFlight.disallow'}], 'messages': []},
        '__typename': 'DigitalConnectOriginalResponse'},
        'getStorefrontConfig': {'privacySettings': {'isEnabled': False,
                                                    'maskFrequentFlyerNumber': False,
                                                    'maskPhoneNumber': False,
                                                    'maskEmailAddress': False,
                                                    'maskDateOfBirth': False,
                                                    'maskTravelDocument': False,
                                                    '__typename': 'StorefrontConfigPrivacySettings'},
                                '__typename': 'StorefrontConfig'}},
        'extensions': {}})
    model = builder.build()
    print(json.dumps(model.__dict__))
